# General Vars
ros_workspace: /tmp/autoware
ros_source_dir:  "{{ ros_workspace }}/src"
ros_build_dir: "{{ ros_workspace }}/build"
ros_install_dir: "/opt/autoware/{{ ros_distro }}"

# Requirement role vars
ros_distro: humble
ros_distro_type: base
collection_name: autoware_universe

repositories_files:
  - build_depend.repos
